### ISSUE TITLE
Add ups apc

### ISSUE THREAD

**Issue by Samir-driod** [networkupstools/nut#1731]
Hi,
Can you add the "apc bk650ei"upc.

**Comment by jimklimov** [comment]
To HCL? Have you tested it? Otherwise, generally it requires someone with the hardware to check if current drivers already work, or (for usbhid and snmp) use a generation script to get a data dump and make a new subdriver, or a willing developer (not my role) to cooperate with a device owner to exchange data dumps, vendor docs, and driver builds to test...

**Comment by Samir-driod** [comment]
i will check
