### ISSUE TITLE
upsd + OpenSSL + OS X: error on initial SSL handshake

### ISSUE THREAD

**Issue by clepple** [networkupstools/nut#202]
Built NUT 2.7.2+ (2e3fb64) on OS X 10.9 with OpenSSL 0.9.8zd (vendor-provided) and OpenSSL 1.0.2a (Fink). Followed SSL setup instructions to create dummy server certificate. `upsd` does not fully accept connections:

`upsd[27047]: Unknown return value from SSL_accept: Resource temporarily unavailable`

And `upsc` shows the following:
```
$ upsc -l
SSL_connect do not accept handshake.: Undefined error: 0
ssl_error() EOF from client
Error while connecting to localhost, disconnect
Error: SSL error: error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure
```

**Comment by jimklimov** [comment]
Hopefully actually fixed with recent merges to the master branch (for more context see #3344, #3330, #1711).

Testing welcome, with eventual v2.8.5 release or custom builds of the master branch before that, see https://github.com/networkupstools/nut/wiki/Building-NUT-for-in%E2%80%90place-upgrades-or-non%E2%80%90disruptive-tests
