### ISSUE TITLE
BX500MI compatibility

### ISSUE THREAD

**Issue by tonygh77** [networkupstools/nut#2533]
Can anyone give me some feedback on using this APC with NUT
Thank you for your time

**Comment by desertwitch** [comment]
The BX series is compatible with NUT, but seems affected by a hardware/firmware strangeness: https://github.com/networkupstools/nut/issues/2347
The issue seems limited to intermittent bogus statuses being presented to the user in the SYSLOG.

Otherwise it should work "normally" with the `usbhid-ups` driver when connected by USB.
Check here for configuration notes: https://networkupstools.org/docs/user-manual.chunked/Configuration_notes.html
Check here for driver-specific configuration: https://networkupstools.org/docs/man/usbhid-ups.html
