### ISSUE TITLE
Nut Master won't allow Slave on different network

### ISSUE THREAD

**Issue by soydemadrid** [networkupstools/nut#344]
I've tried everything I can and even posted on the Mailinglist for help. But whatever I try I cannot get my Nut Slave to connect to my Master.

I have two servers in the same room and housed in the same cabinet, as such they need to share the same UPS.

The problem is they are on different networks and not on the same LAN.

If I connect them on the same LAN for testing the NUT client will read and report from the master. But as soon as I put them on their own correct networks this won't work.

I've tried disabling firewalls, adding "allowfrom" in upsd.users and other things I've read online, but can't get to the bottom of how to allow an outside client/slave IP to work with a master on a different network.

Can anyone please help?

Thanks very much. I don't know if this is an issue as such, a bug or a feature - but does anyone know how I can achieve this as obviously I'm worried that in a power out my slave will hard shutdown unexpectedly.

Thanks again.

**Comment by clepple** [comment]
Closing this issue because it seems to be the same question as http://lists.alioth.debian.org/pipermail/nut-upsuser/2016-November/010425.html and http://lists.alioth.debian.org/pipermail/nut-upsuser/2016-October/010370.html

Please reopen if not, and be sure to include some information as mentioned here: http://networkupstools.org/support.html#_request_help
