### ISSUE TITLE
Nut-scanner not included in latest debian package

### ISSUE THREAD

**Issue by Harvie** [networkupstools/nut#474]
There's no nut-scanner on latest Debian.

**Comment by clepple** [comment]
It doesn't look like it was in jessie, either. The `nut-scanner` binary would probably need to be in a separate package due to its dependencies, but I don't see it in the [package search](https://packages.debian.org/search?suite=jessie&section=all&arch=any&searchon=contents&keywords=nut-scanner)

The right place for this is a wishlist bug in Debian: https://www.debian.org/Bugs/Reporting

If you do file a bug there, feel free to list the URL here.
