### ISSUE TITLE
usbhid-ups: FSD fails due to existing driver running (USB device claimed)

### ISSUE THREAD

**Issue by danielfdickinson** [networkupstools/nut#602]
I'm working on the NUT 2.7.4 package for OpenWrt (https://github.com/openwrt/packages/tree/master/net/nut), and a user reported that their test of ``usbdrvctl shutdown`` failed,  On further debugging ``/lib/nut/usbhid-ups -a upsname -k -DDD`` reports:

````
Network UPS Tools - Generic HID driver 0.41 (reboot-7879-gc4e16b43a0)
USB communication driver 0.33
   0.000000     debug level is '3'
   0.003905     upsdrv_initups...
   0.010870     Checking device (0463/FFFF) (001/003)
   0.493632     - VendorID: 0463
   0.501316     - ProductID: ffff
   0.501412     - Manufacturer: EATON
   0.501487     - Product: Eaton 5P
   0.501562     - Serial Number: H38348439
   0.501636     - Bus: 001
   0.501710     - Device release number: 0100
   0.501781     Trying to match device
   0.501946     Device matches
   0.502085     failed to claim USB device: Resource busy
   0.502196     failed to detach kernel driver from USB device: No such file or directory
   0.502308     failed to claim USB device: Resource busy
   0.502412     failed to detach kernel driver from USB device: No such file or directory
   0.502525     failed to claim USB device: Resource busy
   0.502632     failed to detach kernel driver from USB device: No such file or directory
   0.502742     failed to claim USB device: Resource busy
   0.502849     failed to detach kernel driver from USB device: No such file or directory
   0.502948     Can't claim USB device [0463:ffff]: No such file or directory
````

This occurs regardless of running driver, upsd, and upsdrvctl as root or driver, and upsd as nut with appropriate permissions on the usb device and usbdrvctl as root, so it's NOT a permissions problem.

Looking at the source code in ``main.c`` line 599, I see

``        if ((nut_debug_level == 0) && (!do_forceshutdown)) {
``

surrounding the code that shuts down an existing driver.  Since on the DUT there are no kernel modules accessing any USB device (i.e. no usbhid module, although results are the same if it's present too), nor any other program accessing the usb device, the EBUSY is coming from the currently running driver and the fact that

````
                               if (usb_detach_kernel_driver_np(udev, 0) < 0) {
                                        upsdebugx(2, "failed to detach kernel driver from USB device: %s", usb_strerror());
                                } else {
                                        upsdebugx(2, "detached kernel driver from USB device...");
                                }
````
is obviously failing to remove the existing driver instance.

Since CLI use of the driver is not attaching to the existing instance in order to access the USB device the new FSD instance fails to claim the USB device.  (Also usbhid-ups at least never releases the device unless the device becomes disconnected for some other reason).

So it looks to me like either the expectation that ``usb_detach_kernel_driver_np`` will detach a *user* (root or user nut) is false.  Not sure if that's intended in modern kernels (4.14 and later or not; actually I believe this also occurs with 4.9) as a result of driver changes if there is some capability that is needed that has been removed for user processes in OpenWrt (if so, do you know which it would be?).

At present I'm planning on testing a patch that remove the !do_forceshutdown() test on the killing off of an existing driver instance so that the FSD instance can claim the driver.

If there is something else going on here, or a better fix for 2.7.4, please let me know.

**Comment by cshoredaniel** [comment]
Ok, that didn't work, but it looks like the issue may actually be that the lack of any kernel thing claiming the device results in a error code for the detach function, which confuses libusb-0.1 (or libusb-compat).

**Comment by cshoredaniel** [comment]
So, it seems that part of my problem has been the driver respawning.  So I'm taking a different tack and going to try sending SIGUSR2 to the driver to get it to issue a forced shutdown.  Does newer (i.e. not yet in a release) code already do something like that?

**Comment by cshoredaniel** [comment]
Thank you for your quick response!

SIGUSR2 and SIGUSR1 are 'up for grabs' by daemons who want to respond to a signal other than the pre-defined purposes like TERM INT, etc.  (As you might have guessed it stands for user1 and user2). It's kind of like the local0..local7 syslog stuff.  Although I realized just a few minutes ago doing an FSD on a signal is a potential local DoS (any use can signal an FSD).  So I guess I'll just have  document "use this (e.g.) ``/etc/init.d/nut-server shutdown`` command which makes sure everything is stopped and doesn't come back up.  I will also have to make sure that upsmon -c fsd (and the usual LB stuff) calls that appropriate script too else FSD will never happen.  Are there similar caveats with systemd (I'll have to dig at the systemd services and see if there is some useful suggestions there).
The respawning procd stuff is fairly new to OpenWrt (before it was busybox init).

**Comment by clepple** [comment]
I'm not convinced that using something like SIGUSR1 or SIGUSR2 is a bad idea compared to the current NUT solution of stopping the daemons and restarting just the driver with `-k`, but I think it just shifts the problem slightly. You still need to make sure that the signal is sent late enough in the system shutdown sequence so that other daemons are not still shutting down when the power gets cut.

The only users allowed to signal a NUT driver are other NUT processes (assuming a single UID for NUT, where full privilege separation hasn't been implemented) or a process that has root privileges, so I am not sure your local DoS comment stands (unless the NUT processes are started under a user ID shared with other processes).

With SysV-style run levels, I think the intent was that you could put the `upsdrvctl shutdown` command in an S-level script, after all of the runlevel 2 and 3 processes (including upsd and upsmon) had stopped. I haven't looked into how this is done on systemd, but I mentioned the "conflicts" term because that seems to be a recommended way to shut down systemd services in favor starting another service.

Do you have any other pointers to procd documentation? This is what I found:
* https://wiki.openwrt.org/doc/techref/procd
* https://openwrt.org/docs/guide-developer/procd

**Comment by cshoredaniel** [comment]
@clepple Heh, was editing my response as you responded; hope it helps.

**Comment by cshoredaniel** [comment]
@clepple Ah, I didn't realize NUT was limiting who could send it signals.  That does rather make a difference.

**Comment by clepple** [comment]
The drivers don't do anything special besides dropping root privileges to protect themselves from signals - it's the same as for most HTTP daemons, for instance.

Thanks for pointing out the edits - GitHub doesn't seem to send notifications on edits to existing posts, either in the GUI or over email.

I can't say I have looked at the differences between foreground and background recently, but I know I was able to get things to "just work" with OS X launchd by passing a single `-D` and redirecting stdout/stderr to null. There is the PID file problem mentioned in #168, but if the init system is monitoring a process in the foreground, it doesn't need the PID file since it got the PID from the return value of `fork()` (and if the init system respawns the process, it is probably better for failure bookkeeping to use the init system's restart command than to kill the process directly).

**Comment by cshoredaniel** [comment]
Ok so -D is working fine with what I'm working on now and as long as drivers are already stopped, upsdrvctl works fine.  I've got FSD working in the current OpenWrt stuff now, although I haven't pushed there yet as I still am doing some debugging of minor nits.

On another note, would it be of interest to do 'proper' autoconf and install of scripts used by OpenWrt (so they're incorporated in your tree), or does it make a difference since it's probably rather a niche scenario?

**Comment by clepple** [comment]
Although we have some systemd and distribution-specific scripts in the NUT tree, they are frequently out-of-date. With RedHat's wide gap between the enterprise distributions and Fedora, our advice for users who need new packages is to start from their distribution's spec files, and add in the new NUT source code.

I am not opposed to adding a `README.OpenWrt.md` (or whatever format) file in the `nut/scripts/` directory that points to the link you mentioned. We can also update the [binary packages](https://networkupstools.org/download.html#_binary_packages) link on the web page.

I will also have to check the OpenWrt link later to see what you are looking for with the autoconf integration. We do generate the udev and hotplug files that are part of the NUT tarball by parsing the driver source code, but those scripts are a mess (IMHO) and should be rewritten before we add any other destination file format. If you just need substitution for the user/group, that shouldn't be too hard to do from .in files, but if it is another syntax entirely, then I can see the need for something more integrated.

**Comment by cshoredaniel** [comment]
I'll make it easy .. the relevant bit is here (not autoconf'ed yet):
````
	# Mangle libhid.usermap into a format (hotplug shell script) useful for OpenWrt
        define Package/nut-driver-usbhid-ups/install
		$(INSTALL_DIR) $$(1)/lib/nut $$(1)/etc/hotplug.d/usb
		$(CP) $$(PKG_INSTALL_DIR)/lib/nut/usbhid-ups $$(1)/lib/nut/
		$(INSTALL_BIN) ./files/30-libhid-ups.head $$(1)/etc/hotplug.d/usb/30-libhid-ups
		$(CP) $(PKG_INSTALL_DIR)/etc/hotplug/usb/libhid.usermap $(PKG_BUILD_DIR)/30-libhid-ups.middle
		$(SED) '/^$$$$$$$$/d' \
			-e '/^#/d' \
			-E -e 's:^[^ ][^ ]*  *0x0003  *0x0{0,3}([^ ][^ ]*)  *0x{0,3}*([^ ][^ ]*).*:\1/\2/* | \\:' \
		$(PKG_BUILD_DIR)/30-libhid-ups.middle
		tail -n+2 $(PKG_BUILD_DIR)/30-libhid-ups.middle >>$$(1)/etc/hotplug.d/usb/30-libhid-ups
		cat ./files/30-libhid-ups.tail >>$$(1)/etc/hotplug.d/usb/30-libhid-ups
        endef
````
But obviously that only picks up usbhid - wondering if there are any other similar files scattered through the tree.

**Comment by clepple** [comment]
I'm not sure if I'm reading that block of code correctly, or if it is just taken out of context. It looks like it's for a single driver (`usbhid-ups`), yet the upstream NUT hotplug/udev files cover all of the USB drivers (including `tripplite_usb`, `richcomm_usb`, `nutdrv_qx` when built with USB support, etc). The exact reasons are probably lost to history, but in Debian, we actually moved from a separate package containing all of the USB drivers to a unified "server" package with `upsd` and all of the drivers (serial and USB). Not saying that it couldn't be split out for another packaging system (and I know it makes sense given the filesystem size constraints for OpenWrt), but if I had to do that, I'd put the hotplug data files in a separate package that all of the other USB drivers depend on as well. I suspect the hotplug info for all of the USB drivers was combined into a single file to reduce the number of directory entries that needed to be scanned every time something was plugged in.

If you are looking to change how the hotplug files are generated, and split them out per driver, see `nut/tools/nut-usbinfo.pl`, which still has the driver info as it builds the files. This is one of the scripts I was referring to in the previous comment - don't say I didn't warn you :-) (The `nut/scripts/udev` files do have driver names, but they are in the comments, and might be annoying to parse without awk or a higher-level scripting language.)

Not sure which other `*.in` files might be appropriate. IPMI tends not to be in low-end motherboards, and the rest seem to be unrelated to drivers. The Avahi service definition is marginally useful - only the `nut-scanner` binary looks for the mDNS entry, to my knowledge.

**Comment by cshoredaniel** [comment]
Ok so libhid.usermap is actually all drivers, not just usbhid-ups?  In that case I'll move that code to a the common driver code (which is currently with nut-server package since AFAIK one can't use the driver without the server, and for OpenWrt the default is to build only the USB drivers with options for serial and SNMP drivers for DIY builds).  I was merely mislead by the name, not thinking the effort of splitting a small shell script is worth it.

Thanks again!

**Comment by cshoredaniel** [comment]
Thanks for your help!  There are some minor nits left in the OpenWrt packages but at least in master things are now well (and hopefully will soon backport to current stable (18.06) series).
